name: Default

on:
  schedule:
    - cron: '33 15 * * *'
  push:
    branches: [ "latest" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "latest" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Initialize repository
        uses: actions/checkout@v4

      - name: Initialize the build
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}

      - name: Build
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: NUGET_PASSWORD=${{ secrets.REGISTRY_TOKEN }}
          